name: 'Shared setup steps'
description: 'Shared setup steps for testings'

runs:
  using: 'composite'
  steps:
    - name: Read .nvmrc
      id: nvmrc
      run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      shell: bash
    - name: 'Set up NodeJS'
      uses: 'actions/setup-node@v4'
      with:
        node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'
    - name: 'Cache node modules'
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      shell: bash
      run: npm list

    - name: Install dependencies
      shell: bash
      run: npm install
