name: Run tests
on: [pull_request]

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN_READ}}

jobs:
  install-modules:
    runs-on: [self-hosted, cere-io-large]
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup tests'
        uses: './.github/actions/setup'

  unit-tests:
    runs-on: [self-hosted, cere-io-large]
    needs: install-modules
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup tests'
        uses: './.github/actions/setup'
      - name: 'Run tests'
        run: npm run test

  build-test:
    runs-on: [self-hosted, cere-io-large]
    needs: install-modules
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup tests'
        uses: './.github/actions/setup'
      - name: 'Check ts build'
        run: npm run build

  lint-tests:
    runs-on: [self-hosted, cere-io-large]
    needs: install-modules
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup tests'
        uses: './.github/actions/setup'
      - name: 'Check ESLint + Typecheck'
        run: npm run lint
      - name: 'Check codestyle'
        run: npm run codestyle
      - name: 'Check that all copies are extracted'
        run: npm run extract-copies-check
